services:
  whisper-cpp:
    build:
      context: ./whisper-cpp
      args:
        - WHISPER_CPP_VERSION=1.7.4
        - BUILD_FROM=intel/oneapi:2025.0.1-0-devel-ubuntu24.04
    restart: unless-stopped
    depends_on:
      model-download:
        condition: service_completed_successfully
    # Change user to the one that will run the container
    #user: 1000:1000
    #group_add:
      # Change this number to match your "render" host group id
      # You can get the id number by running: getent group render
     # - "107"
    security_opt:
      - no-new-privileges:true
    volumes:
      - type: bind
      # Please change /path/to/models to a real directory the user the service is running as can read and write to
      # Make sure to do the same for model-download service too
        source: /share/CACHEDEV1_DATA/whisper-models
        target: /models
    networks:
      whisper: {}
    hostname: whispercpp
    devices:
      - /dev/dri:/dev/dri
      - /dev/dri/renderD128:/dev/dri/renderD128
      - /dev/dri/card0:/dev/dri/card0
    environment:
      - PUID=1000  # Your QNAP User ID
      - PGID=100 
      - SYCL_CACHE_PERSISTENT=1
      - SYCL_CACHE_DIR=/models/sycl_cache
      - SYCL_DEVICE_ALLOWLIST=BackendName:level_zero
      - ONEAPI_DEVICE_SELECTOR=level_zero:0
    command: build/bin/whisper-server -l ${WHISPER_LANG} -bs ${WHISPER_BEAM_SIZE} -m /models/ggml-${WHISPER_MODEL}.bin --host 0.0.0.0 --port 8910 --suppress-nst --prompt "${WHISPER_PROMPT}"
  wyoming-api:
    build:
      context: ./wyoming-api
      args:
        - BUILD_FROM=debian:bookworm-slim
    restart: unless-stopped
    depends_on:
      whisper-cpp:
        condition: service_started
    security_opt:
      - no-new-privileges:true
    # Change user to the one that will run the container
    #user: 1000:1000
    environment:
      - PUID=1000  # Your QNAP User ID
      - PGID=100 
    networks:
      whisper: {}
    ports:
      - 7891:7891
    command: script/run --uri tcp://0.0.0.0:7891 --api http://whispercpp:8910/inference
  model-download:
    security_opt:
      - no-new-privileges:true
    #user: 1000:1000
    build:
      context: ./model-download
    volumes:
      - type: bind
      # Please change /path/to/models to a real directory the user the service is running as can read and write to
      # Make sure to do the same for whisper-cpp service too
        source: /share/CACHEDEV1_DATA/whisper-models
        target: /models
    restart: no
    networks:
      whisper: {}
    environment:
      - PUID=1000  # Your QNAP User ID
      - PGID=100 
      - MODEL=${WHISPER_MODEL}
networks:
  whisper: {}
